// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VestibularAPI.infraestructure.model.context;

#nullable disable

namespace VestibularAPI.Migrations
{
    [DbContext(typeof(VestibularContext))]
    [Migration("20250206235651_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VestibularAPI.infraestructure.model.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("Cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<int>("VagasDisponiveis")
                        .HasColumnType("int")
                        .HasColumnName("VagasDisponiveis");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<Guid>("IdCandidato")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCandidato");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCurso");

                    b.Property<Guid>("IdProcessoSeletivo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProcessoSeletivo");

                    b.Property<int>("NumeroDeInscricao")
                        .HasColumnType("int")
                        .HasColumnName("NumeroDeInscricao");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdProcessoSeletivo");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.ProcessoSeletivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataDeFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataDeFim");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataDeInicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("ProcessosSeletivos");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.Inscricao", b =>
                {
                    b.HasOne("VestibularAPI.infraestructure.model.Candidato", "Candidato")
                        .WithMany("Incricoes")
                        .HasForeignKey("IdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestibularAPI.infraestructure.model.Curso", "Curso")
                        .WithMany("Incricoes")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestibularAPI.infraestructure.model.ProcessoSeletivo", "ProcessoSeletivo")
                        .WithMany("Incricoes")
                        .HasForeignKey("IdProcessoSeletivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Curso");

                    b.Navigation("ProcessoSeletivo");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.Candidato", b =>
                {
                    b.Navigation("Incricoes");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.Curso", b =>
                {
                    b.Navigation("Incricoes");
                });

            modelBuilder.Entity("VestibularAPI.infraestructure.model.ProcessoSeletivo", b =>
                {
                    b.Navigation("Incricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
